const codigos_participantes_permitidos = [
    { id: 0, codigo: "535B" },
    { id: 1, codigo: "740J" },
    { id: 2, codigo: "231I" },
    { id: 3, codigo: "362E" },
    { id: 4, codigo: "378Z" },
    { id: 5, codigo: "582A" },
    { id: 6, codigo: "947Y" },
    { id: 7, codigo: "367F" },
    { id: 8, codigo: "874S" },
    { id: 9, codigo: "670Q" },
    { id: 10, codigo: "760X" },
    { id: 11, codigo: "400J" },
    { id: 12, codigo: "487G" },
    { id: 13, codigo: "737E" },
    { id: 14, codigo: "128Z" },
    { id: 15, codigo: "105G" },
    { id: 16, codigo: "226C" },
    { id: 17, codigo: "738X" },
    { id: 18, codigo: "923N" },
    { id: 19, codigo: "910S" },
    { id: 20, codigo: "834E" },
    { id: 21, codigo: "336E" },
    { id: 22, codigo: "124A" },
    { id: 23, codigo: "458M" },
    { id: 24, codigo: "566I" },
    { id: 25, codigo: "240Y" },
    { id: 26, codigo: "167N" },
    { id: 27, codigo: "506R" },
    { id: 28, codigo: "322I" },
    { id: 29, codigo: "874B" },
    { id: 30, codigo: "218T" },
    { id: 31, codigo: "517F" },
    { id: 32, codigo: "172U" },
    { id: 33, codigo: "134Ñ" },
    { id: 34, codigo: "651R" },
    { id: 35, codigo: "276M" },
    { id: 36, codigo: "627F" },
    { id: 37, codigo: "723I" },
    { id: 38, codigo: "531J" },
    { id: 39, codigo: "366V" },
    { id: 40, codigo: "146B" },
    { id: 41, codigo: "238J" },
    { id: 42, codigo: "823E" },
    { id: 43, codigo: "872B" },
    { id: 44, codigo: "133G" },
    { id: 45, codigo: "486T" },
    { id: 46, codigo: "462R" },
    { id: 47, codigo: "710S" },
    { id: 48, codigo: "478M" },
    { id: 49, codigo: "622F" }
]//codigos  que se pueden usar para entrar a votar una para cada participante
const historial_votaciones_usuario = [//!(servidor)
    [[null, null], [null, null], [null, null], [null, null], [null, null]],
    [[null, null], [null, null], [null, null], [null, null], [null, null]],
    [[null, null], [null, null], [null, null], [null, null], [null, null]],
    [[null, null], [null, null], [null, null], [null, null], [null, null]]
]//2 votos por categoria;null:voto no realizado,!null:voto realizado, el numero es el numero de indentificacion del votado,el indice es el id de cada participante
const datos_presentados_votaciones = [//sin terminar
    //4ºA
    { id: 0, nombre: 'Zaira Blanco', clase: '4ºA', foto: null, descripcion: '' },
    { id: 1, nombre: 'Aitana Casais', clase: '4ºA', foto: null, descripcion: '' },
    { id: 2, nombre: 'Pablo Mato', clase: '4ºA', foto: null, descripcion: '' },
    //4ºC
    { id: 3, nombre: 'Andrea Barreiro', clase: '4ºC', foto: null, descripcion: '' },
    { id: 4, nombre: 'Pablo Capeáns', clase: '4ºC', foto: null, descripcion: '' },
    { id: 5, nombre: 'Antía Cisneros', clase: '4ºC', foto: null, descripcion: '' },
    { id: 6, nombre: 'Gonzalo Cuns', clase: '4ºC', foto: null, descripcion: '' },
    { id: 7, nombre: 'Baifeng Dong', clase: '4ºC', foto: null, descripcion: '' },
    { id: 8, nombre: 'Lara Gabín', clase: '4ºC', foto: null, descripcion: '' },
    { id: 9, nombre: 'Mariña García', clase: '4ºC', foto: null, descripcion: '' },
    { id: 10, nombre: 'Raúl García', clase: '4ºC', foto: null, descripcion: '' },
    { id: 11, nombre: 'Pablo Hermida', clase: '4ºC', foto: null, descripcion: '' },
    { id: 12, nombre: 'Paula Lamas', clase: '4ºC', foto: null, descripcion: '' },
    { id: 13, nombre: 'Gabriela Moreira', clase: '4ºC', foto: null, descripcion: '' },
    { id: 14, nombre: 'Ainhoa Pais', clase: '4ºC', foto: null, descripcion: '' },
    { id: 15, nombre: 'Sara Parajó', clase: '4ºC', foto: null, descripcion: '' },
    { id: 16, nombre: 'Antía Quinteiro', clase: '4ºC', foto: null, descripcion: '' },
    { id: 17, nombre: 'Fatima Rial', clase: '4ºC', foto: null, descripcion: '' },
    { id: 18, nombre: 'Santiago Andrés', clase: '4ºC', foto: null, descripcion: '' },
    { id: 19, nombre: 'Ariana Suárez', clase: '4ºC', foto: null, descripcion: '' },
    { id: 20, nombre: 'Oscar Suárez', clase: '4ºC', foto: null, descripcion: '' },
    { id: 21, nombre: 'Noela Vázquez', clase: '4ºC', foto: null, descripcion: '' },
    { id: 22, nombre: 'Brais Vilacoba', clase: '4ºC', foto: null, descripcion: '' },
    { id: 23, nombre: 'Mateo González', clase: '4ºC', foto: 'MateoGonzalez.jpg', descripcion: 'Cada día mejor que el anterior. El día difícil no es en el que no haces nada.🃏' },
    { id: 24, nombre: 'Inés Rivas', clase: '4ºC', foto: null, descripcion: '' },
    //4ºB
    { id: 25, nombre: 'Daniel Forján', clase: '4ºB', foto: null, descripcion: '' },
    { id: 26, nombre: 'Mateo García', clase: '4ºB', foto: null, descripcion: '' },
    { id: 27, nombre: 'Pablo Nieto', clase: '4ºB', foto: null, descripcion: '' },
    { id: 28, nombre: 'Anxo Noya', clase: '4ºB', foto: null, descripcion: '' },
    { id: 29, nombre: 'Iago Toja', clase: '4ºB', foto: null, descripcion: '' },
    { id: 30, nombre: 'Sergio Vieites', clase: '4ºB', foto: null, descripcion: '' },
    { id: 31, nombre: 'José Villar', clase: '4ºB', foto: null, descripcion: '' },
    { id: 32, nombre: 'Aldara Tuñas', clase: '4ºB', foto: null, descripcion: '' },
    { id: 33, nombre: 'Alexandra Sanmartín', clase: '4ºB', foto: null, descripcion: '' },
    { id: 34, nombre: 'Sofia Liñares', clase: '4ºB', foto: null, descripcion: '' },
    { id: 35, nombre: 'Laura Leis', clase: '4ºB', foto: null, descripcion: '' },
    { id: 36, nombre: 'Tomás Dosil', clase: '4ºB', foto: null, descripcion: '' },
    { id: 37, nombre: 'Yasmín', clase: '4ºB', foto: null, descripcion: '' },
    { id: 38, nombre: 'Xoán', clase: '4ºB', foto: null, descripcion: '' },
    { id: 39, nombre: 'Diego', clase: '4ºB', foto: null, descripcion: '' },
    { id: 40, nombre: 'Noa Beiroa', clase: '4ºB', foto: null, descripcion: '' },
    { id: 41, nombre: 'Marina', clase: '4ºB', foto: null, descripcion: '' }

]//datos de las personas que se pueden votar
const votos_recibidos_presentados_votaciones = [//!(servidor)
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
]//votos que tiene cada persona presentada en cada categoria, el numero del indice es el numero de identificacion del candiato;los nuemros son los votos recibidos en cada categoria
const nombres_categorias_votaciones = [
    "Amable",
    "Compañeirismo",
    "Traballadora",
    "Graciosa",
    "Lista"
]//categorias !(estas son temporales)